#  Copyright 2019 U.C. Berkeley RISE Lab
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  Modifications copyright (C) 2021 Taras Lykhenko, Rafael Soares

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: function-nodes
  labels:
    role: function
spec:
  selector:
    matchLabels:
      role: function
  template:
    metadata:
      labels:
        role: function
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              role: function
      restartPolicy: Always
      volumes:
      - name: ipc
        emptyDir: {}
      containers:
      - name: function-1
        image: jrafaelsoares/faastcc_cloudburst
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1G"
            cpu: "1"
          limits:
            memory: "2G"
            cpu: "2"
        env:
        - name: LIBC_FATAL_STDERR_
          value: "1"
        - name: ROUTE_ADDR
          value: ROUTE_ADDR_DUMMY
        - name: MGMT_IP
          value: MGMT_IP_DUMMY
        - name: SCHED_IPS
          value: SCHED_IPS_DUMMY
        - name: THREAD_ID
          value: "0"
        - name: ROLE
          value: executor
        - name: REPO_ORG
          value: FaaSTCC
        - name: REPO_BRANCH
          value: master
        - name: ANNA_REPO_ORG
          value: FaaSTCC
        - name: ANNA_REPO_BRANCH
          value: master
        volumeMounts:
        - mountPath: /requests
          name: ipc
      - name: function-2
        image: jrafaelsoares/faastcc_cloudburst
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1G"
            cpu: "1"
          limits:
            memory: "2G"
            cpu: "2"
        env:
        - name: LIBC_FATAL_STDERR_
          value: "1"
        - name: ROUTE_ADDR
          value: ROUTE_ADDR_DUMMY
        - name: MGMT_IP
          value: MGMT_IP_DUMMY
        - name: SCHED_IPS
          value: SCHED_IPS_DUMMY
        - name: THREAD_ID
          value: "1"
        - name: ROLE
          value: executor
        - name: REPO_ORG
          value: FaaSTCC
        - name: REPO_BRANCH
          value: master
        - name: ANNA_REPO_ORG
          value: FaaSTCC
        - name: ANNA_REPO_BRANCH
          value: master
        volumeMounts:
        - mountPath: /requests
          name: ipc
      - name: function-3
        image: jrafaelsoares/faastcc_cloudburst
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1G"
            cpu: "1"
          limits:
            memory: "2G"
            cpu: "2"
        env:
        - name: LIBC_FATAL_STDERR_
          value: "1"
        - name: ROUTE_ADDR
          value: ROUTE_ADDR_DUMMY
        - name: MGMT_IP
          value: MGMT_IP_DUMMY
        - name: SCHED_IPS
          value: SCHED_IPS_DUMMY
        - name: THREAD_ID
          value: "2"
        - name: ROLE
          value: executor
        - name: REPO_ORG
          value: FaaSTCC
        - name: REPO_BRANCH
          value: master
        - name: ANNA_REPO_ORG
          value: FaaSTCC
        - name: ANNA_REPO_BRANCH
          value: master
        volumeMounts:
        - mountPath: /requests
          name: ipc
      - name: cache-container
        image: jrafaelsoares/faastcc_cache
        imagePullPolicy: Always
        resources:
          requests:
            memory: "8G"
            cpu: "1"
          limits:
            memory: "16G"
            cpu: "2"
        env:
        - name: LIBC_FATAL_STDERR_
          value: "1"
        - name: ROUTE_ADDR
          value: ROUTE_ADDR_DUMMY
        - name: MGMT_IP
          value: MGMT_IP_DUMMY
        - name: REPO_ORG
          value: FaaSTCC
        - name: REPO_BRANCH
          value: master
        volumeMounts:
        - mountPath: /requests
          name: ipc
      nodeSelector:
        type: F
