#!/bin/bash

# you can change ~/hydro-taras to whatever you like
export HYDRO_HOME=~/hydro-storage

#cd pods
kubectl apply --namespace=default -f $HYDRO_HOME/cluster/hydro/cluster/yaml/pods/redis.yml
#kubectl apply --namespace=default -f mongodb.yml
#cd ..

kubectl config set-context --current --namespace=default
kubectl delete namespaces hydro
kubectl create namespace hydro

#echo "FINISHED NAMESPACE"
#kubectl create secret docker-registry regcred --namespace=hydro --docker-username= --docker-password=
#echo "FINISHED SECRET"
kubectl config set-context --current --namespace=hydro

rm -rf $HYDRO_HOME
mkdir $HYDRO_HOME
cd $HYDRO_HOME
git clone https://github.com/tiagopmartins/TotalOrderExperiment cluster

redis_ip=$(kubectl get nodes -o=jsonpath='{.items[0].status.addresses[0].address}')
echo $redis_ip

#cd ~/Desktop/PrompTCC/TccExperimentStorage
#cd TccExperimentStorage

#echo $! > save_pid.txt
cd cluster
python3 -m hydro.cluster.create_cluster -s 1 -c 1 -l True
